export * from "./account/Account.tsx";
export * from "./about/AboutUs.tsx";
export * from "./checkout/CheckoutPage.tsx";
export * from "./home/HomePage/HomePage.tsx";
export * from "./platform/PlatformPage.tsx";
export * from "./products/ProductPage.tsx";
export * from "./search/SearchPage/SearchPage.tsx";
export * from "./special_offers/SpecialOffers.tsx";
export * from "./tracking/TrackingPage.tsx";
export * from "./account/Recovery/Recovery.tsx"